baseURL: "https://focused-torvalds-7cfd03.netlify.app/" 
disablePathToLower: yes
languageCode: en-us
title: "IDS 2935: The Future of Rain Forests"
theme: docter
params:
  author: Emilio Bruna
  author_url: http://Brunalab.org 
  home: https://github.com/embruna
  hosted_on: Netlify
  hosted_on_url: https://focused-torvalds-7cfd03.netlify.app/
  mainSections: page
  repo: https://github.com/BrunaLab/IDS2395_website/
  repo_host: Github
