baseURL = "https://focused-torvalds-7cfd03.netlify.app/"
disablePathToLower = false
languageCode = "en-us"
title = "IDS2935"
theme = "docter"

[params]
  # the name of your project and a link back to the home page
  home = "The Future of Rain Forests (IDS 2935 - Fall 2021 - Quest 2)"
  # A small snippet of text above the sidebar:
  # subtitle = ""

  author = "Emilio M. Bruna"
  author_url= "https://github.com/BrunaLab"

  # Point readers to your repo and invite them to edit pages 
  repo_host = "Github"
  repo = "https://github.com/BrunaLab/IDS2935_website"

  # Add a reference to a logo, which will appear in the top right
  # logourl = "/images/brunalab_logo.png"
  # logoalt = ""

  # Mention your hosting provider 
  # hosted_on = "hosting provider XYZ"
  # hosted_on_url= "#"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["posts"]

  # brand color
   brand_color = "#347C2C"